### ISSUE TITLE
Compatibility with 0.5.0-M1

### ISSUE THREAD

**Issue by arnaudbriche** [thinkaurelius/titan-experimental#1]
Hi, 

I cannot managed to find the answer on the Aurelius mailing list, so I'll try here: are the in-memory backends (hazelcast and infinispan) abandonned ? If not, are they compatible with Titan 0.5.0-M1 ?

**Comment by mbroecheler** [comment]
I think I just responded to your email. Short story: we are not actively developing the Hazelcast adapter at this point. Using one of the other storage adapters in conjunction with Titan's caching layer provides very good performance.
